on: 
  workflow_dispatch:



jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"
      - name: Install dependencies
      uses
